version: '3.8'
services:

  chatterley-db:
    container_name: chatterley-db
    image: postgres:13
    ports:
      - 6432:5432
    environment:
      POSTGRES_DB: chatterley
      POSTGRES_USER: chatterley
      POSTGRES_PASSWORD: chatterley
    volumes:
      - /var/pg/chatterley-db:/var/lib/postgresql/data

  chatterley-mongodb:
    image: mongo:latest
    container_name: chatterley-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

volumes:
  mongodb_data:
